Models/Inscritos.cs
using System.ComponentModel.DataAnnotations;

namespace FuncionesLinq.Models
{
    public class Inscritos
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Administrador")]
        public int Addby { get; set; }
        [Required]
        [Display(Name = "Alumno")]
        public int Idalumno { get; set; }
        [Required]
        [Display(Name = "Curso")]
        public int Idcurso { get; set; }
        public bool Status { get; set; } = true;
        public DateTime FechaAdd { get; set; } = DateTime.Now;
        
    }
}

Controllers/InscritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FuncionesLinq.Data;
using FuncionesLinq.Models;
using UniversidadInterfaces.Interfaces;

namespace FuncionesLinq.Controllers
{
    public class InscritosController : Controller
    {
        private readonly FuncDBContext _context;
        private readonly Iestudios _estudios;

        public InscritosController(FuncDBContext context, Iestudios estudios)
        {
            _context = context;
            _estudios = estudios;
        }

        // GET: Inscritos
        public async Task<IActionResult> Index()
        {
            var usuarios_       = _context.Usuarios.ToList();
            var alumnos_        = _context.Alumnos.ToList();
            var cursos_         = _context.Cursos.OrderBy(c => c.nIvel).ToList();
            ViewBag.usuarios    = usuarios_;
            ViewBag.alumnos     = alumnos_;
            ViewBag.cursos      = cursos_;


            var listaInscritos = from d in _context.Inscritos
            join u in _context.Usuarios on d.Addby equals u.Id
            join a in _context.Alumnos on d.Idalumno equals a.Id
            join c in _context.Cursos on d.Idcurso equals c.Id
            select new
            {
                administrador_  = u.Name,
                alumno_         = a.Name,
                cursos_         = c.CursoName,
                status_         = d.Status,
                fecha_          = d.FechaAdd
                // other assignments
            };
            ViewBag.listaInscritos = listaInscritos;

            int cantidadCursos = listaInscritos.Count();

            ViewBag.msgAlumnos = _estudios.cursosPorCategoria(cantidadCursos);

            return View(await _context.Inscritos.ToListAsync());
        }

        public async Task<IActionResult> Nivel()
        {
            var usuarios_ = _context.Usuarios.ToList();
            var alumnos_ = _context.Alumnos.ToList();
            var cursos_ = _context.Cursos.OrderBy(c => c.nIvel).ToList();
            ViewBag.usuarios = usuarios_;
            ViewBag.alumnos = alumnos_;
            ViewBag.cursos = cursos_;

            var listaInscritos = from d in _context.Inscritos
                                 join u in _context.Usuarios on d.Addby equals u.Id
                                 join a in _context.Alumnos on d.Idalumno equals a.Id
                                 join c in _context.Cursos on d.Idcurso equals c.Id
                                 select new
                                 {
                                     administrador_ = u.Name,
                                     alumno_ = a.Name,
                                     cursos_ = c.CursoName,
                                     status_ = d.Status,
                                     fecha_ = d.FechaAdd,
                                     nivel_ = c.nIvel
                                     // other assignments
                                 };

            ViewBag.listaInscritos = listaInscritos;

            return View();
        }



        public async Task<IActionResult> Categoria(int SearchCategoria)
        {
            var usuarios_ = _context.Usuarios.ToList();
            var alumnos_ = _context.Alumnos.ToList();
            var cursos_ = _context.Cursos.OrderBy(c => c.nIvel).ToList();
            ViewBag.usuarios = usuarios_;
            ViewBag.alumnos = alumnos_;
            ViewBag.cursos = cursos_;

            var listaInscritos = from d in _context.Inscritos
                                 join u in _context.Usuarios on d.Addby equals u.Id
                                 join a in _context.Alumnos on d.Idalumno equals a.Id
                                 join c in _context.Cursos on d.Idcurso equals c.Id
                                 select new
                                 {
                                     administrador_ = u.Name,
                                     alumno_ = a.Name,
                                     cursos_ = c.CursoName,
                                     status_ = d.Status,
                                     fecha_ = d.FechaAdd,
                                     nivel_ = c.nIvel,
                                     categoria_ = c.Categoria
                                     // other assignments
                                 };
            ViewBag.listaInscritos = listaInscritos;

            if (SearchCategoria >= 0)
            {
                var listaInscritos2 = from d in _context.Inscritos
                                      join c in _context.Cursos on d.Idcurso equals c.Id
                                      join u in _context.Usuarios on d.Addby equals u.Id
                                      join a in _context.Alumnos on d.Idalumno equals a.Id                                     
                                      where ((int)c.Categoria).Equals(SearchCategoria)
                                      select new
                                      {
                                          administrador_ = u.Name,
                                          alumno_ = a.Name,
                                          cursos_ = c.CursoName,
                                          status_ = d.Status,
                                          fecha_ = d.FechaAdd,
                                          nivel_ = c.nIvel,
                                          categoria_ = c.Categoria
                                          // other assignments
                                      };
                int cantidadCursos = listaInscritos2.Count();

                ViewBag.msgCursos = _estudios.cursosPorCategoria(cantidadCursos);
                ViewBag.listaInscritos = listaInscritos2;
            }


            return View();
        }


        public async Task<IActionResult> SoloCursos(int SearchCurso)
        {
            var usuarios_ = _context.Usuarios.ToList();
            var alumnos_ = _context.Alumnos.ToList();
            var cursos_ = _context.Cursos.OrderBy(c => c.nIvel).ToList();
            ViewBag.usuarios = usuarios_;
            ViewBag.alumnos = alumnos_;
            ViewBag.cursos = cursos_;
            int cursosQty = cursos_.Count;
            ViewBag.cursosQty = cursosQty;

            if (SearchCurso >= 0)
            {
                var listaInscritos2 = from d in _context.Inscritos
                                      join c in _context.Cursos on d.Idcurso equals c.Id
                                      join u in _context.Usuarios on d.Addby equals u.Id
                                      join a in _context.Alumnos on d.Idalumno equals a.Id
                                      where (c.Id).Equals(SearchCurso)
                                      select new
                                      {
                                          administrador_ = u.Name,
                                          alumno_ = a.Name,
                                          cursos_ = c.CursoName,
                                          status_ = d.Status,
                                          fecha_ = d.FechaAdd,
                                          nivel_ = c.nIvel,
                                          categoria_ = c.Categoria
                                          // other assignments
                                      };

                ViewBag.listaInscritos = listaInscritos2;
            }

            return View();
        }



        // GET: Inscritos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Inscritos == null)
            {
                return NotFound();
            }

            var inscritos = await _context.Inscritos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inscritos == null)
            {
                return NotFound();
            }

            return View(inscritos);
        }

        // GET: Inscritos/Create
        public IActionResult Create()
        {
            var usuarios_       = _context.Usuarios.ToList();
            var alumnos_        = _context.Alumnos.ToList();
            var cursos_         = _context.Cursos.OrderBy(c => c.nIvel).ToList();
            ViewBag.usuarios    = usuarios_;
            int usuariosQty     = usuarios_.Count;
            ViewBag.usuariosQty = usuariosQty;
            ViewBag.alumnos     = alumnos_;
            int alumnosQty      = alumnos_.Count;
            ViewBag.alumnosQty  = alumnosQty;           
            ViewBag.cursos      = cursos_;            
            int cursosQty       = cursos_.Count;
            ViewBag.cursosQty   = cursosQty;


            return View();
        }

        // POST: Inscritos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Addby,Idalumno,Idcurso,Status,FechaAdd")] Inscritos inscritos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inscritos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(inscritos);
        }

        // GET: Inscritos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Inscritos == null)
            {
                return NotFound();
            }

            var inscritos = await _context.Inscritos.FindAsync(id);
            if (inscritos == null)
            {
                return NotFound();
            }
            return View(inscritos);
        }

Views/Inscritos/Categoria.cshtml
@model FuncionesLinq.Models.Inscritos

@{
    ViewData["Title"] = "Categoria";
}

<h1>Categoria</h1>
<hr />
<form asp-controller="Inscritos" asp-action="Categoria">
<div class="input-group mb-3 w-50">
        <select name="SearchCategoria" class="form-select form-control">
          <option value=-1>Todos</option>
          <option value=0>FrontEnd</option>
          <option value=1>BackEnd</option>
          <option value=2>FullStack</option>
          
        </select>
  <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
</div>
</form>
<hr />
<h1 class="text-danger">@ViewBag.msgCursos</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Categoria
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addby)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idalumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idcurso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAdd)
            </th>
            
        </tr>
    </thead>
    <tbody>
@if(ViewBag.listaInscritos != null){

    @foreach (var item in ViewBag.listaInscritos) {
            <tr>
                <td>
                    @item.categoria_
                </td>
                <td>
                    @item.administrador_
                </td>
                <td>
                    @item.alumno_
                </td>
                <td>
                    @item.cursos_
                </td>
                <td>
                    @item.status_ 
                </td>
                <td>
                    @item.fecha_
                </td>
@*                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>*@
            </tr>
    }
}
    </tbody>
</table>

Views/Inscritos/Create.cshtml
@model FuncionesLinq.Models.Inscritos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Inscritos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Addby" class="control-label"></label>
                
                @if(ViewBag.usuariosQty > 0)
                {
                        <select asp-for="Addby" class="form-select form-control">
                        @foreach (var usuario in ViewBag.usuarios)
                        {
                            <option value="@usuario.Id">@usuario.Name</option>
                        }
                    </select>
                }else
                {
                    <p>Debes agregar un administrador</p>
                }
                <span asp-validation-for="Addby" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idalumno" class="control-label"></label>
                @if(ViewBag.alumnosQty > 0)
                {
                        <select asp-for="Idalumno" class="form-select form-control">
                        @foreach (var alumno in ViewBag.alumnos)
                        {
                            <option value="@alumno.Id">@alumno.Name</option>
                        }
                    </select>
                }else
                {
                    <p>Debes agregar un alumno</p>
                }
                <span asp-validation-for="Idalumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idcurso" class="control-label"></label>
                @if(ViewBag.cursosQty > 0)
                {
                        <select asp-for="Idcurso" class="form-select form-control">
                        @foreach (var curso in ViewBag.cursos)
                        {
                            <option value="@curso.Id">@curso.CursoName</option>
                        }
                    </select>
                }else
                {
                    <p>Debes agregar un curso</p>
                }
                <span asp-validation-for="Idcurso" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Inscritos/Delete.cshtml
@model FuncionesLinq.Models.Inscritos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inscritos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Addby)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Addby)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idalumno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idalumno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idcurso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idcurso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAdd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAdd)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Inscritos/Details.cshtml
@model FuncionesLinq.Models.Inscritos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Inscritos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Addby)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Addby)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idalumno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idalumno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idcurso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idcurso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAdd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAdd)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Inscritos/Edit.cshtml
@model FuncionesLinq.Models.Inscritos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Inscritos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Addby" class="control-label"></label>
                <input asp-for="Addby" class="form-control" />
                <span asp-validation-for="Addby" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idalumno" class="control-label"></label>
                <input asp-for="Idalumno" class="form-control" />
                <span asp-validation-for="Idalumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idcurso" class="control-label"></label>
                <input asp-for="Idcurso" class="form-control" />
                <span asp-validation-for="Idcurso" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FechaAdd" class="control-label"></label>
                <input asp-for="FechaAdd" class="form-control" />
                <span asp-validation-for="FechaAdd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Inscritos/Index.cshtml
@model IEnumerable<FuncionesLinq.Models.Inscritos>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<hr />
<h1 class="text-danger">@ViewBag.msgAlumnos</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Addby)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idalumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idcurso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAdd)
            </th>
            
        </tr>
    </thead>
    <tbody>
@if(ViewBag.listaInscritos != null){

    @foreach (var item in ViewBag.listaInscritos) {
            <tr>
                <td>
                    @item.administrador_
                </td>
                <td>
                    @item.alumno_
                </td>
                <td>
                    @item.cursos_
                </td>
                <td>
                    @item.status_ 
                </td>
                <td>
                    @item.fecha_
                </td>
@*                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>*@
            </tr>
    }
}
    </tbody>
</table>

Views/Inscritos/Nivel.cshtml
@model FuncionesLinq.Models.Inscritos

@{
    ViewData["Title"] = "Nivel";
}

<h1>Nivel</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Nivel
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addby)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idalumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idcurso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAdd)
            </th>
            
        </tr>
    </thead>
    <tbody>
@if(ViewBag.listaInscritos != null){

    @foreach (var item in ViewBag.listaInscritos) {
            <tr>
                <td>
                    @item.nivel_
                </td>
                <td>
                    @item.administrador_
                </td>
                <td>
                    @item.alumno_
                </td>
                <td>
                    @item.cursos_
                </td>
                <td>
                    @item.status_ 
                </td>
                <td>
                    @item.fecha_
                </td>
@*                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>*@
            </tr>
    }
}
    </tbody>
</table>

Views/Inscritos/SoloCursos.cshtml
@model FuncionesLinq.Models.Inscritos

@{
    ViewData["Title"] = "Cursos";
}

<h1>Solo cursos</h1>
<hr />
<form asp-controller="Inscritos" asp-action="SoloCursos">
<div class="input-group mb-3 w-50">
        @if (ViewBag.cursosQty > 0)
        {
            <select name="SearchCurso" class="form-select form-control">
                @foreach(var it in ViewBag.cursos)
                {
                  <option value="@it.Id">@it.CursoName</option>  
                }
            </select>
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
        }
</div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Categoria
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addby)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idalumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idcurso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAdd)
            </th>
            
        </tr>
    </thead>
    <tbody>
@if(ViewBag.listaInscritos != null){

    @foreach (var item in ViewBag.listaInscritos) {
            <tr>
                <td>
                    @item.categoria_
                </td>
                <td>
                    @item.administrador_
                </td>
                <td>
                    @item.alumno_
                </td>
                <td>
                    @item.cursos_
                </td>
                <td>
                    @item.status_ 
                </td>
                <td>
                    @item.fecha_
                </td>
@*                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>*@
            </tr>
    }
}
    </tbody>
</table>